apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-projectplanner
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-projectplanner
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}
