apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-projectplanner-pv
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}
